// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetFilteredTasks(arg1:string,arg2:string):Promise<Array<main.Task>>;

export function GetTasks():Promise<Array<main.Task>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleTask(arg1:number):Promise<void>;
